name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - master # Adjust this to the branch you want to trigger the build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU (for multi-arch emulation)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx (for cross-platform builds)
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Store this in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Store this in GitHub Secrets

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ndrdmarshmallow/housie:latest, ndrdmarshmallow/housie:1.0.0
